### ISSUE TITLE
[monitor-hw] consider the firmware update of redfish

### ISSUE THREAD

**Issue by satoru-takeuchi** [cybozu-go/neco#295] opened 2019-06-04 06:13 UTC
## What

If redfish version updates after starting monitor-hw, the data format of redfish would change.
Then monitor-hw fails to parse the response from redfish.

For example, we encountered the problem that monitor-hw failed to get some storage metrics.

## How

Periodically check redfish version and change the parsing rule of monitor-hw.

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment] 2019-06-04 06:37
Duplicate of https://app.zenhub.com/workspaces/neco-5ca28d055128c041a68c0a8f/issues/cybozu-go/setup-hw/15

**Closed by ymmt2005** 2019-06-04 06:37 UTC
