### ISSUE TITLE
ingress-health returns 5XX frequently

### ISSUE THREAD

**Issue by tapih** [cybozu-go/neco#1270] opened 2020-12-11 06:59 UTC
**Describe the bug**

As shown below, ingress-health seems to be returning 5XX frequently.

![ingress-health-metrics.PNG](https://images.zenhubusercontent.com/5cb4031a148b9f0190c0ae03/e09e6197-5fc3-4f77-a90d-b3d4b6b009d3)

This behavior is unintended, so examine what is causing this.
Tracking [here](https://bozuman.cybozu.com/k/#/space/3801/thread/27736/2671689)

**Environments**
https://github.com/cybozu-go/neco/releases/tag/release-2020.12.11-11507

**To Reproduce**

Just launch the Neco environment on GCP.

**Expected behavior**

The ingress-watcher gets 200 stably while ingress-health is running.

**Additional context**

**Comment by binoue** [comment] 2020-12-24 02:14
Waiting for upstream support: https://github.com/projectcontour/contour/issues/3214

**Comment by ymmt2005** [comment] 2021-03-04 01:43
We could not improve Contour and could not find the root cause too.

As we have already mitigated this by adjusting the monitoring threshold, I'm closing this.

**Closed by ymmt2005** 2021-03-04 01:43 UTC
Labels: bug
