### ISSUE TITLE
Prepare self-build CSI container images for Rook/Ceph.

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#1015] opened 2020-06-16 06:19 UTC
## What

Some pods which are generated by the rook operator use upstream CSI container images.
So prepare self-build CSI container images and use it.

## How

Prepare the following images in neco-containers.

- quay.io/cephcsi/cephcsi:v2.1.1

- quay.io/k8scsi/csi-attacher:v2.1.0
- quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
- quay.io/k8scsi/csi-provisioner:v1.4.0
- quay.io/k8scsi/csi-resizer:v0.4.0
- quay.io/k8scsi/csi-snapshotter:v1.2.2

## Checklist

- [ ] Finish implementation of the issue
- [ ] Test all functions
- [ ] Have enough logs to trace activities
- [ ] Notify developers of necessary actions

**Comment by ymmt2005** [comment] 2020-06-17 01:34
Duplicate of #940

**Closed by ymmt2005** 2020-06-17 01:34 UTC
